[default]
dynaconf_env="DEFAULT"
fastapi_title = ""
fastapi_description = ""
fastapi_summary = ""
loggers = [{"name"="pyfat", "log_file"="../../logs/pyfat.log", "log_level"=10, "log_format" = "%(asctime)s %(levelname)s: %(message)s", "log_date_format" = "%Y-%m-%d %H:%M:%S" }]
#log_file = "@format {env[BASE_DIR]}/logs/pyfat.log"
vlo_solr_url = 'http://localhost:8183/solr/vlo-index'
metrics_file = "clarin_fip_metrics_v0.3.yaml"
metrics_pckg = "pyfip.resources.metrics"
nspace_file = "namespaces.json"
nspace_pckg = "pyfip.resources"


[development]
dynaconf_env="DEVELOPMENT"
fastapi_title = ""
fastapi_description = ""
fastapi_summary = ""
vlo_solr_url = 'http://localhost:8183/solr/vlo-index'


[staging]
dynaconf_env="STAGING"

[testing]
dynaconf_env="TESTING"


[production]
dynaconf_env="PRODUCTION"

#NOTSET=0
#DEBUG=10
#INFO=20
#WARN=30
#ERROR=40
#CRITICAL=50